spring.application.name=SB-SMS-SERVICE
# embedded tomcat port no ( to change we use server.port)
server.port=4444

#Database connection properties
# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/mydatabase
spring.datasource.username=root
spring.datasource.password=your_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

## MySQL Dialect (optional for newer Spring Boot versions)
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#Application Properties
sms.save.success = "SUCCESS : Supplier Object Saved"
sms.db.fail = "FAILED : DB Error"
sms.update.success = "SUCCESS : Supplier Object Updated"
sms.delete.success = "SUCCESS : Supplier Object Deleted"
sms.invalid.not-found = "Supplier Details Not Found"
sms.invalid.supplier-details= "FAILED : Invalid Supplier Object Details"

#ip address 
eureka.instance.hostname=localhost

#Stop registering as a client. It is a Server
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
