spring.application.name=SB-MSA-ServiceRegistry

#Port number for service registry  default port no. => 8761
server.port=8761

#ip address 
eureka.instance.hostname=localhost

#Stop registering as a client. It is a Server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false